config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: redirect('/articles')

  resources :articles, only: [:show, :index]
  resources :players, only: [:index]
  resources :coaches, only: [:index]
  resources :comments, only: [:index, :new, :create]

  scope :pages do
    get :resources, to: 'pages#resources', as: :pages_resources
    get :about, to: 'pages#about', as: :pages_about
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  mount_uploader :picture, PictureUploader

  def self.coach_category
    coach_articles = Article.where(coach: true)
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/coach.rb
class Coach < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  mount_uploader :picture, PictureUploader

  def self.group_position
    positions = Player.select(:position).map(&:position).uniq
    sorted_positions = Player.order('position, player_string ASC')
    final_arr = Array.new
    positions.each do |position|
     final_arr << sorted_positions.select{ |player| player.position == position }
    end
    return final_arr
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order(created_at: :desc)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = @article.comments.all
    @comment = @article.comments.build
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :subheading, :article_body, :picture)
    end
end

app/controllers/coaches_controller.rb
class CoachesController < InheritedResources::Base

  def index
    @coaches = Coach.all
    @articles = Article.coach_category
  end

  def show
    render plain: '404 not found', status: 404
  end

  private

    def coach_params
      params.require(:coach).permit(:first_name, :last_name, :coach_position, :article, :picture, :strength, :weakness)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    render plain: '404 not found', status: 404
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    render plain: '404 not found', status: 404
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@comment.article_id) }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment updated' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment destroyed' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :article_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def resources
  end
end

app/controllers/players_controller.rb
class PlayersController < InheritedResources::Base

  def index
    @positions = Player.group_position
  end

  def show
    render plain: '404 not found', status: 404
  end

  private

    def player_params
      params.require(:player).permit(:first_name, :last_name, :position, :article, :picture, :strength, :weakness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :subheading %>
    <%= form.text_area :subheading, id: :article_subheading %>
  </div>

  <div class="field">
    <%= form.label :article_body %>
    <%= form.text_area :article_body, id: :article_article_body, class: "tinymce"  %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :idea_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= tinymce %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="page-container">
  <% @articles.each do |article| %>
    <div class="card mb-3">
      <div class="card-block px-4 py-2">
        <div class="article-index-container">
          <div class="article-index-text-container">
            <h1><%= link_to article.title, article_path(article), class: 'card-title py-2' %></h1>
            <div class="card-body"><%= article.subheading %></div>
          </div>
          <%= image_tag article.picture_url(:thumb), class: 'article-index-thumbnail' if article.picture.present? %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="card mb-3">
  <div class="card-block px-4 py-2">
    <h1><%= @article.title %></h1>
    <div class="subheading-date">
      <h3 class="date">Posted on <%= @article.created_at.to_s.first(-13) %></h3>
    </div>
    <div class="wysiwyg-content"><%= @article.article_body.html_safe %></div>
  </div>
</div>

<div class="card mb-3">
  <div class="card-block px-4 py-2">
    <h2>Comments</h2>
      <ul>
        <% @comments.each do |comment| %>
          <li class="comment">
          <strong><%= comment.user_name %></strong>
          <br>
          <p><%= comment.body %></p>
        </li>
        <% end %>
      </ul>
    <%= render partial: 'comments/form', locals: { comment: @comment } %>
  </div>
</div>

app/views/coaches/_form.html.erb
<%= form_with(model: coach, local: true) do |form| %>
  <% if coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% coach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :coach_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :coach_last_name %>
  </div>

  <div class="field">
    <%= form.label :coach_position %>
    <%= form.text_field :coach_position, id: :coach_coach_position %>
  </div>

  <div class="field">
    <%= form.label :article %>
    <%= form.text_field :article, id: :coach_article %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :idea_picture %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.text_field :strength, id: :coach_strength %>
  </div>

  <div class="field">
    <%= form.label :weakness %>
    <%= form.text_field :weakness, id: :coach_weakness %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Editing Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<div class="page-container">
  <div class="card mb-7 static-page">
    <div class="card-block px-4 py-5">
      <h1>Content coming soon</h1>
    </div>
  </div>
</div>

<table style="width:100%">
  <tbody>
    <tr>
      <td></td>
      <td class="cell-container">
        <% coach_idx = @coaches.find_index do |coach| coach.coach_position == 'HC'  %>
          <div class="coach-card-container">
            <%= image_tag(coach.picture_url, width: 60, rel: "popover", data: {
              toggle: "popover",
              trigger: "hover",
              placement: "top",
              container: "body",
              title: "#{coach.first_name} #{coach.last_name}",
              content: "#{image_tag(coach.picture_url)}<br>
              #{coach.coach_position} <br>
              Strengths: #{coach.strength}<br>
              Weaknesses: #{coach.weakness}<br>
              #{coach.article}"
            }) if coach.picture.present? %>
            <p><%= coach.last_name %></p>
          </div>
         <% end %>
      </td>
      <td></td>
    </tr>
    <tr>
      <td class="cell-container">
        <% coach_idx = @coaches.find_index do |coach| coach.coach_position == 'OC'  %>
          <div class="coach-card-container">
            <%= image_tag(coach.picture_url, width: 60, rel: "popover", data: {
              toggle: "popover",
              trigger: "hover",
              placement: "top",
              container: "body",
              title: "#{coach.first_name} #{coach.last_name}",
              content: "#{image_tag(coach.picture_url)}<br>
              #{coach.coach_position} <br>
              Strengths: #{coach.strength}<br>
              Weaknesses: #{coach.weakness}<br>
              #{coach.article}"
            }) if coach.picture.present? %>
            <div><%= coach.last_name %></div>
          </div>
         <% end %>
      </td>
      <td></td>
      <td class="cell-container">
        <% coach_idx = @coaches.find_index do |coach| coach.coach_position == 'DC'  %>
          <div class="coach-card-container">
            <%= image_tag(coach.picture_url, width: 60, rel: "popover", data: {
              toggle: "popover",
              trigger: "hover",
              placement: "top",
              container: "body",
              title: "#{coach.first_name} #{coach.last_name}",
              content: "#{image_tag(coach.picture_url)}<br>
              #{coach.coach_position} <br>
              Strengths: #{coach.strength}<br>
              Weaknesses: #{coach.weakness}<br>
              #{coach.article}"
            }) if coach.picture.present? %>
            <div><%= coach.last_name %></div>
          </div>
         <% end %>
      </td>
    </tr>
  </tbody>
</table>

<div class="page-container">
  <% @articles.each do |article| article.coach == true %>
    <div class="card mb-3">
      <div class="card-block px-4 py-2">
        <div class="article-index-container">
          <div class="article-index-text-container">
            <h1><%= link_to article.title, article_path(article), class: 'card-title py-2' %></h1>
            <div class="card-subtitle"><%= article.subheading %></div>
          </div>
          <%= image_tag article.picture_url(:thumb), class: 'article-index-thumbnail' if article.picture.present? %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/coaches/new.html.erb
<h1>New Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @coach.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @coach.last_name %>
</p>

<p>
  <strong>Coach position:</strong>
  <%= @coach.coach_position %>
</p>

<p>
  <strong>Article:</strong>
  <%= @coach.article %>
</p>

<p>
  <strong>Picture:</strong>
</p>

<p>
  <strong>Strength:</strong>
  <%= @coach.strength %>
</p>

<p>
  <strong>Weakness:</strong>
  <%= @coach.weakness %>
</p>

<%= link_to 'Back', coaches_path %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :user_name, placeholder: 'Username', id: :comment_user_name, class: "form-control comment-input"  %>
  </div>

  <div class="field">
    <%= form.text_area :body, placeholder: 'Enter your comment...', id: :comment_body, class: "form-control comment-input mceNoEditor" %>
  </div>

  <div class="field">
    <%= form.hidden_field :article_id, id: :comment_article_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.article_id %></td>
        <td><%= link_to 'Show', comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<%= link_to 'Back', comments_path %>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :player_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :player_last_name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position, id: :player_position %>
  </div>

  <div class="field">
    <%= form.label :article %>
    <%= form.text_field :article, id: :player_article %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :player_picture %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.text_field :strength, id: :player_strength %>
  </div>

  <div class="field">
    <%= form.label :weakness %>
    <%= form.text_field :weakness, id: :player_weakness %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @player.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @player.last_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.position %>
</p>

<p>
  <strong>Article:</strong>
  <%= @player.article %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@player.picture_url, width: 600) if @player.picture.present? %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @player.strength %>
</p>

<p>
  <strong>Weakness:</strong>
  <%= @player.weakness %>
</p>

<%= link_to 'Back', players_path %>