config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: redirect('/articles')

  resources :articles, only: [:show, :index]
  resources :players, only: [:index]
  resources :coaches, only: [:index]
  resources :comments, only: [:index, :new, :create]

  scope :pages do
    get :resources, to: 'pages#resources', as: :pages_resources
    get :about, to: 'pages#about', as: :pages_about
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  mount_uploader :picture, PictureUploader

  def self.coach_category
    coach_articles = Article.where(coach: true)
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/coach.rb
class Coach < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  mount_uploader :picture, PictureUploader

  def self.group_position
    positions = Player.select(:position).map(&:position).uniq
    sorted_positions = Player.order('position, player_string ASC')
    final_arr = Array.new
    positions.each do |position|
     final_arr << sorted_positions.select{ |player| player.position == position }
    end
    return final_arr
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order(created_at: :desc)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = @article.comments.all
    @comment = @article.comments.build
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :subheading, :article_body, :picture)
    end
end

app/controllers/coaches_controller.rb
class CoachesController < InheritedResources::Base

  def index
    @coaches = Coach.all
    @articles = Article.coach_category
  end

  def show
    render plain: '404 not found', status: 404
  end

  private

    def coach_params
      params.require(:coach).permit(:first_name, :last_name, :coach_position, :article, :picture, :strength, :weakness)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    render plain: '404 not found', status: 404
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    render plain: '404 not found', status: 404
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@comment.article_id) }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment updated' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment destroyed' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :article_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def resources
  end
end

app/controllers/players_controller.rb
class PlayersController < InheritedResources::Base

  def index
    @positions = Player.group_position
  end

  def show
    render plain: '404 not found', status: 404
  end

  private

    def player_params
      params.require(:player).permit(:first_name, :last_name, :position, :article, :picture, :strength, :weakness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p class="site-footer-container">Eagles Linc © <%= Time.now.year %></p>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-static-top navbar-light navigation">
  <%= link_to image_tag('EL_final.png', width: '250', height: '220'), root_path %>&emsp;
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavMenu" aria-controls="navbarNavMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="banner">Your home of the Super Bowl champion Philadelphia Eagles</div>
  <div class="collapse navbar-collapse justify-content-end pr-2" id="navbarNavMenu">
    <div class="navbar-nav">
      <%= link_to 'Articles', articles_path, class: 'nav-item nav-link' %>
      <%= link_to 'Depth Chart', players_path, class: 'nav-item nav-link' %>
      <%= link_to 'Front Office', pages_resources_path, class: 'nav-item nav-link' %>
      <%= link_to 'Coaches\' Corner', coaches_path, class: 'nav-item nav-link' %>
	  <%= link_to 'About', pages_about_path, class: 'nav-item nav-link' %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eagles Linc</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/nav' %>
      <div class="flex-container">
        <div class="container">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        <%= yield %>
      </div>
    </div>
      <%= render 'layouts/footer' %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
    <script id="twitter-wjs" type="text/javascript" async defer src="//platform.twitter.com/widgets.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="page-container">
  <div class="card mb-7 static-page">
    <div class="card-block px-4 py-5">
      <h1>About</h1>
      <p>Welcome to Eagles Linc, a new website designed to cover everything from gameplans to the personnel decisions of your Super Bowl 52 champion Philadelphia Eagles. A fan since 2004, I have written previously for Bleeding Green Nation and Pro Football Focus, in addition to being published in print in the Eagles Annual.</p>
    </div>
  </div>
</div>

app/views/pages/resources.html.erb
<div class="page-container">
  <div class="card mb-7 static-page">
    <div class="card-block px-4 py-5">
      <h1>Content coming soon</h1>
    </div>
  </div>
</div>